### ISSUE TITLE
Z3 master@6bacf09  assertion violation src/util/ref_vector.h Line: 91 sz <= m_nodes.size() during Augur contracts analysis

### ISSUE THREAD

**Issue by cryptomental** [Z3Prover/z3#1776]
The assertion appeared after #1766 was fixed.

Steps to reproduce

```
 $  git clone https://github.com/cryptomental/augur-core.git
 $  cd augur-core/
 $  git co feature/ignore-selected-oyente-issues
 $  npm run docker:run:test:security:oyente
```

The first run will take 10-15 minutes due to Docker Oyente/Z3 dependencies installation, next runs assert is reproduces in less than one minute.

FYI: @NikolajBjorner this is the assertion I mentioned at #1766 , please let me now if you need any support with reproducing this issue. It should be straightforward for Linux/MacOS with Docker installed.

**Comment by cryptomental** [comment]
To reproduce the issue under gdb inside docker container:

```
$  pip install pdbpp
$  apt-get install -y python-dev gdb
$  ln -fs /usr/lib/python2.7/plat-x86_64-linux-gnu/_sysconfigdata.py /usr/lib/python2.7/
$  ln -fs /usr/lib/python2.7/plat-x86_64-linux-gnu/_sysconfigdata_nd.py /usr/lib/python2.7/
$  export PYTHONPATH=/usr/lib/python2.7/:/usr/local/lib/python2.7/site-packages:/usr/local/lib/python2.7/lib-dynload/
$  python source/tools/runOyente.py -p -a
```

**Comment by NikolajBjorner** [comment]
1. I was able to run the log file, but it didn't exhibit the crash.
2. The gdb stack is very useful.
3. Based on the stack I hardened a couple of places that could be the root cause of what you observe. They are checked into master.
4. I don't have a working Docker setup on my dev machines. After some hours of installing either the ubuntu parallels version, which doesn't support some required kernel features, and the windows Docker variant, which requires some BIOS settings I haven't been able to get to change in spite of several reboots, I am putting this on the side for now. I hope you understand and that you can check if we are making progress. I understand it is the way to go and your repro steps are transparent. It could take me some time to get the preliminaries working.

**Comment by cryptomental** [comment]
@NikolajBjorner yes, thank you a lot for all the effort. If I remember correctly VirtualBox on Windows worked for me quite well. Other than free tier of Amazon AWS could work as well. I will re-run the hardened version and let's see what happens.

**Comment by cryptomental** [comment]
@NikolajBjorner there is bad news and there is good news.

Bad news is that hardened version still fails with the same error.
Good news is that I found https://labs.play-with-docker.com

They offer a free remote shell session that lasts for 4 hours with Alpine linux instance with 8vCPU cores, 32 GB ram and 4,7GB space for Docker images to experiment. It just requires a Docker account that can be created for free.

Z3 builds there in 5-6 minutes, the complete Docker run takes ~10-11 minutes.
I had to remove /var/lib/docker/containers as I ran out of space but later everything works, including gdb.


```
$  rm -rf /var/lib/docker/containers
$  rm -rf /var/lib/docker/overlay2/
$  apk add --update nodejs nodejs-npm
$  git clone https://github.com/cryptomental/augur-core.git
$  cd augur-core/
$  git checkout feature/ignore-selected-oyente-issues
$  npm run docker:run:test:security:oyente
```

wait until fails... and then start the container in interactive privileged mode:

```
$ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
<none>              <none>              72f3a8dd65e3        17 minutes ago      3.15GB
python              2.7.13              ac9424878b8f        10 months ago       679MB
[node1] (local) root@192.168.0.23 ~/augur-core
```

```
[node1] (local) root@192.168.0.23 ~/augur-core
$ docker run -it --privileged --entrypoint=/bin/bash 72f3a8dd65e3


#  pip install pdbpp
#  apt-get install -y python-dev gdb
#  ln -fs /usr/lib/python2.7/plat-x86_64-linux-gnu/_sysconfigdata.py /usr/lib/python2.7/#  ln -fs /usr/lib/python2.7/plat-x86_64-linux-gnu/_sysconfigdata_nd.py /usr/lib/python2.7/#  export PYTHONPATH=/usr/lib/python2.7/:/usr/local/lib/python2.7/site-packages:/usr/local/lib/python2.7/lib-dynload/
#  python source/tools/runOyente.py -p -a
```

![screenshot from 2018-07-31 09 31 18](https://user-images.githubusercontent.com/20819151/43445448-a4e7885c-94a6-11e8-99a7-6954f98a81ea.png)

![screenshot from 2018-07-31 09 39 18](https://user-images.githubusercontent.com/20819151/43445460-ab2a3570-94a6-11e8-943f-97bfcb61688a.png)

**Comment by cryptomental** [comment]
They offer a web interface to the console but Putty / Linux ssh session is much more convenient.

**Comment by NikolajBjorner** [comment]
FYI, your instructions are accurate and helpful. The latest break is patched, but I can so far only reproduce the crash on the docker image. It will update thread when I find out more about the root cause.

**Comment by NikolajBjorner** [comment]
The root cause of this bounds violation is taken care of. 
On the other hand, the alignment of bit-vector sizes isn't fully fixed and I had to revert some changes until I fully understand how to deal with re-entry after cancellation. 
The docker environment works thanks to your instructions; the only real delay at this point is round-tripping repros, porting crashes across environments, and of course identifying the right fix for this.
Based on today's efforts, it is going to take me some more days to sort this out.

Overall I suspect oyente will timeout often on its 100ms budget per call, and furthermore always time out on some of the instructions that use division of bit-vectors. I can try to take snapshots of these runs to figure out where to add more efficient solver, but roundtripping such improvements is typically very long (given that you say oyente doesn't come with active support, taking just soft dependencies seems the more sane approach).

**Comment by cryptomental** [comment]
@NikolajBjorner thank you a lot for the detailed analysis. I am happy that I was able to help with Docker setup and I will patiently wait for the proper solution.

**Comment by NikolajBjorner** [comment]
update: the push from above takes care of quite a bit. I had 3-4 runs that go through end-to-end and seem to report some issues in the contracts (I don't have context to dig into this) and it reports overflow and re-entrancy issues.

These runs are possibly debug builds as I managed to get also a release version to segfault after perhaps running for 20-30 minutes. Unfortunately, I haven't been able to extract a stack or trace for this, mostly due to my lack of skillsets operating the setups/scripts, and partially due to the round-trip time.
If you are able to hit a "bt" on a segfault it could help identify what is going on here.
The main issues reported in the two bugs should be fixed, though.

For about 6000 queries extracted from a run, several of these take more than 100ms, but they all seem to take less than 1s, most of them much less. You can possibly tinker with the timeout for the symbolic execution engine to cover more branches.

**Comment by NikolajBjorner** [comment]
There also seem to be some issues with the Oyente tool itself.
I see stack traces reporting key errors and some layout problems:

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/oyente/symExec.py", line 715, in sym_exec_block
    sym_exec_block(new_params, right_branch, block, depth, func_call, current_func_name)
  File "/usr/local/lib/python2.7/site-packages/oyente/symExec.py", line 665, in sym_exec_block
    sym_exec_block(new_params, successor, block, depth, func_call, current_func_name)
  File "/usr/local/lib/python2.7/site-packages/oyente/symExec.py", line 612, in sym_exec_block
    sym_exec_ins(params, block, instr, func_call, current_func_name)
  File "/usr/local/lib/python2.7/site-packages/oyente/symExec.py", line 1641, in sym_exec_ins
    memory.extend([0] * mem_extend)
OverflowError: cannot fit 'long' into an index-sized integer


Perhaps those who are active on oyente can take a look, e.g. @luongnt95 or @leonardoalt.


I am not sure if Prateek

**Comment by cryptomental** [comment]
Ok thank you @NikolajBjorner a lot for fixing this. I will try to bt the segfault if still happens. I hope the Oyente team will analyse your findings as well. I will also try to find out if tinkering the timeout to 1s will help.
