### ISSUE TITLE
Bad `.dylib` versioning in `pip` package.

### ISSUE THREAD

**Issue by zwimer** [Z3Prover/z3#6651]
The `.dylib` distributed in the `pip` package of `z3` seems to have bad version info in it. Here is a comparison of the version distributed through homebrew vs pip. Notice the pip version lists versions as `0.0.0`.

From `pip`:
```bash
$ otool -L libz3.4.12.dylib
libz3.4.12.dylib:
	libz3.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1311.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 1200.3.0)
```

From `homebrew`:
```bash
$ otool -L libz3.4.12.dylib
libz3.4.12.dylib:
	/opt/homebrew/opt/z3/lib/libz3.4.12.dylib (compatibility version 4.12.0, current version 4.12.1)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 1300.32.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1319.0.0)
```

**Comment by NikolajBjorner** [comment]
12.0 vs 12.1 will be resolved in next release

**Comment by zwimer** [comment]
@NikolajBjorner For clarification, are you saying this `libz3.dylib (compatibility version 0.0.0, current version 0.0.0)` issue happens only on `12.0`; and that the `z3-solver==4.12.1.0` release is distributing the `12.0` library, but this will be fixed on the next release?

The python version installed that has the error above is `z3-solver==4.12.1.0`.

**Comment by NikolajBjorner** [comment]
the version discrepancy between 12.0 and 12.1 should be fixed. There were two releases after each other to fix a local problem.
I don't know about what is the cause of version 0.0.0 showing up and will not be able to address it on my own.

**Comment by zwimer** [comment]
@NikolajBjorner I'm not sure what the `12.0` and `12.1` discrepancy is; both my pip and brew installs are `12.1`. This issue was meant to be about this:

> I don't know about what is the cause of version 0.0.0 showing up and will not be able to address it on my own.

That is the issue I meant to bring to light in this issue. I can re-word the issue above to make this more clear if it was unclear before, but given the issue is still present I think it should be re-opened (I am assuming it was closed due to a misunderstanding, please correct me if I am mistaken).

**Comment by NikolajBjorner** [comment]
what is the fix?

**Comment by zwimer** [comment]
> what is the fix?

I'm not sure what is causing the `0.0.0` version issue; it is only on the `pip` build not the `homebrew` build, so it might be evident in the difference in cmake flags passed during the build step.

What I meant to say was that it might be useful to re-open this issue until the `0.0.0` issue earlier is resolved and add a 'Help Wanted' label to this issue? Either that or open then re-close the issue as "won't fix" if there is no intention to fix this nor be open to PRs for it.

With that in mind, if my initial wording was confusing somehow, please let me know how and I'll edit the initial post (or create a new issue if you prefer) for this `0.0.0` bug.

**Comment by zwimer** [comment]
@NikolajBjorner Just making sure this wasn't forgotten. Should this issue be:
1. Reopened as the issue still presists
2. A new issue made linking this
3. Labeled as a "won't fix"? (github has a special close option for these issues)

Unless I misunderstood, this issue was closed as the issue was misunderstood (perhaps my original description of the problem was unclear? I can edit it if you let me know what part was confusing). Thanks!

**Comment by NikolajBjorner** [comment]
Does anybody know how to fix this?

**Comment by waywardmonkeys** [comment]
Could we have pip use make to do the build instead of the other build system?

**Comment by amanuel2** [comment]
I'm having this issue as well. A simple cargo run from a brand new project results in:

```
--- stderr
dyld[14357]: Library not loaded: /opt/homebrew/opt/z3/lib/libz3.4.12.dylib
  Referenced from: <....> /opt/homebrew/Cellar/llvm/17.0.6/lib/libLLVM.dylib
  Reason: tried: '/opt/homebrew/opt/z3/lib/libz3.4.12.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/z3/lib/libz3.4.12.dylib' (no such file), '/opt/homebrew/opt/z3/lib/libz3.4.12.dylib' (no such file), '/usr/local/lib/libz3.4.12.dylib' (no such file), '/usr/lib/libz3.4.12.dylib' (no such file, not in dyld cache), '/opt/homebrew/Cellar/z3/4.13.0/lib/libz3.4.12.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/Cellar/z3/4.13.0/lib/libz3.4.12.dylib' (no such file), '/opt/homebrew/Cellar/z3/4.13.0/lib/libz3.4.12.dylib' (no such file), '/usr/local/lib/libz3.4.12.dylib' (no such file), '/usr/lib/libz3.4.12.dylib' (no such file, not in dyld cache)
```

Checking in my dylibs, turns out i have libz3.4.13.0.0 instead of libz3.4.12.dylib, would be nice to just target the libz3.dylib which is a symlink to the latest, although not sure if that might cause issues.
